services:
  shmart:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shmart
    ports:
      - "${PORT:-2861}:${PORT:-2861}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:///app/data/local.db
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped

networks:
  default:
    name: shmart-network
